/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Wallpaper = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'featured' : IDL.Bool,
  'tags' : IDL.Vec(IDL.Text),
  'trending' : IDL.Bool,
  'likes' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'addedDate' : IDL.Int,
  'category' : IDL.Text,
  'downloads' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addWallpaper' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Bool, IDL.Bool],
      [IDL.Nat],
      [],
    ),
  'deleteWallpaper' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Wallpaper)], ['query']),
  'getFeatured' : IDL.Func([], [IDL.Vec(Wallpaper)], ['query']),
  'getPopular' : IDL.Func([IDL.Nat], [IDL.Vec(Wallpaper)], ['query']),
  'getRandom' : IDL.Func([], [Wallpaper], []),
  'getTrending' : IDL.Func([], [IDL.Vec(Wallpaper)], ['query']),
  'getWallpaper' : IDL.Func([IDL.Nat], [IDL.Opt(Wallpaper)], ['query']),
  'getWallpaperCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getWallpapers' : IDL.Func([], [IDL.Vec(Wallpaper)], ['query']),
  'incrementDownload' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'likeWallpaper' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'searchWallpapers' : IDL.Func(
      [
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Bool),
        IDL.Opt(IDL.Bool),
      ],
      [IDL.Vec(Wallpaper)],
      ['query'],
    ),
  'updateWallpaper' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Bool,
        IDL.Bool,
      ],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Wallpaper = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'featured' : IDL.Bool,
    'tags' : IDL.Vec(IDL.Text),
    'trending' : IDL.Bool,
    'likes' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'addedDate' : IDL.Int,
    'category' : IDL.Text,
    'downloads' : IDL.Nat,
  });
  
  return IDL.Service({
    'addWallpaper' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Bool, IDL.Bool],
        [IDL.Nat],
        [],
      ),
    'deleteWallpaper' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Wallpaper)], ['query']),
    'getFeatured' : IDL.Func([], [IDL.Vec(Wallpaper)], ['query']),
    'getPopular' : IDL.Func([IDL.Nat], [IDL.Vec(Wallpaper)], ['query']),
    'getRandom' : IDL.Func([], [Wallpaper], []),
    'getTrending' : IDL.Func([], [IDL.Vec(Wallpaper)], ['query']),
    'getWallpaper' : IDL.Func([IDL.Nat], [IDL.Opt(Wallpaper)], ['query']),
    'getWallpaperCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getWallpapers' : IDL.Func([], [IDL.Vec(Wallpaper)], ['query']),
    'incrementDownload' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'likeWallpaper' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'searchWallpapers' : IDL.Func(
        [
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Bool),
          IDL.Opt(IDL.Bool),
        ],
        [IDL.Vec(Wallpaper)],
        ['query'],
      ),
    'updateWallpaper' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Bool,
          IDL.Bool,
        ],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };