/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Wallpaper {
  'id' : bigint,
  'title' : string,
  'featured' : boolean,
  'tags' : Array<string>,
  'trending' : boolean,
  'likes' : bigint,
  'imageUrl' : string,
  'addedDate' : bigint,
  'category' : string,
  'downloads' : bigint,
}
export interface _SERVICE {
  'addWallpaper' : ActorMethod<
    [string, string, string, Array<string>, boolean, boolean],
    bigint
  >,
  'deleteWallpaper' : ActorMethod<[bigint], boolean>,
  'getByCategory' : ActorMethod<[string], Array<Wallpaper>>,
  'getFeatured' : ActorMethod<[], Array<Wallpaper>>,
  'getPopular' : ActorMethod<[bigint], Array<Wallpaper>>,
  'getRandom' : ActorMethod<[], Wallpaper>,
  'getTrending' : ActorMethod<[], Array<Wallpaper>>,
  'getWallpaper' : ActorMethod<[bigint], [] | [Wallpaper]>,
  'getWallpaperCount' : ActorMethod<[], bigint>,
  'getWallpapers' : ActorMethod<[], Array<Wallpaper>>,
  'incrementDownload' : ActorMethod<[bigint], boolean>,
  'likeWallpaper' : ActorMethod<[bigint], boolean>,
  'searchWallpapers' : ActorMethod<
    [string, [] | [string], [] | [bigint], [] | [boolean], [] | [boolean]],
    Array<Wallpaper>
  >,
  'updateWallpaper' : ActorMethod<
    [bigint, string, string, string, Array<string>, boolean, boolean],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];